# After changing this file, check it on:
#   http://lint.travis-ci.org/
sudo: false

language: python

# Python versions to be tested
python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libsuitesparse-dev
    - libgdal-dev
    - graphviz
    - mono-devel

env:
  global:
    - PIP_INSTALL="pip install --upgrade"

before_install:
  - $PIP_INSTALL pip
  - uname -a
  - printenv

install:
  - $PIP_INSTALL atlas numpy scipy matplotlib pytest pandas statsmodels networkx fnss

script:
  - python test.py
